# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]

repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: aafcfb49b50ab95707a13bc7329da421c8740d99
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: 'tests/testthat/.*/.*\.R'
    -   id: roxygenize
        additional_dependencies:
        - r-lib/pkgapi
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          \.github/.*\.yaml|
          touchstone/config\.json|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*-in_tree
          )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
        exclude: >
          (?x)^(
          bench/.*
          )$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
    -   id: require-news-on-push
        name: Require bullet in NEWS.md
        description: NEWS.md must be updated with every PR.
        entry: inst/hooks/require-news-update.R
        stages: [push]
        language: script
        always_run: true
